/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.domains.genesis.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import dev.aurakai.auraframefx.domains.cascade.models.AgentMessage

/**
 *
 *
 * @param status Status of the orchestration (e.g., \"INITIATED\", \"PROCESSING\", \"COMPLETED\", \"FAILED\").
 * @param messages Messages/responses from the orchestrator and involved agents.
 */
@Serializable

data class OrchestrationResponse(

    /* Status of the orchestration (e.g., \"INITIATED\", \"PROCESSING\", \"COMPLETED\", \"FAILED\"). */
    @SerialName(value = "status")
    val status: kotlin.String,

    /* Messages/responses from the orchestrator and involved agents. */
    @SerialName(value = "messages")
    val messages: kotlin.collections.List<AgentMessage>? = null,

    )

