package dev.aurakai.auraframefx.domains.genesis

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
/**
 *
 *
 * @param prompt The prompt/instruction for the AI agent.
 * @param context Additional context (e.g., previous messages, data references).
 */
@Serializable

data class AgentProcessRequest(

    /* The prompt/instruction for the AI agent. */
    @SerialName(value = "prompt")
    val prompt: String,

    /* Additional context (e.g., previous messages, data references). */
    @SerialName(value = "context")
    val context: Map<String, String>? = null,

    )
